#!/usr/bin/env python3

from ektools import ekfile

import sys
import struct

files = sys.argv[1:]
ekfiles = [ekfile(f) for f in files]
iters = [iter(e.datagrams()) for e in ekfiles]
heads = [next(i) for i in iters]

while iters:
    dates = [h[2] for h in heads]
    # find earliest date e
    e = dates.index(min(dates))

    # write out heads[e]
    typ, length, date, message = heads[e]
    out = struct.pack(f'<l{length}sl', length, message, length)
    sys.stdout.buffer.write(out)

    # replace it:
    try:
        heads[e] = next(iters[e])
    except StopIteration:
        iters = iters[:e] + iters[e + 1:]
        heads = heads[:e] + heads[e + 1:]
